name: CI

on:
  push:

jobs:

  nix-build-docs:
    name: Nix build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v17
      - name: Build all packages
        run: nix build -L .#docs

  nix-build-server:
    name: Nix build server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
      - name: Build binplz-server
        run: nix build -L '.#server'
      - name: Build binplz-server shell
        run: nix build -L '.#devShell.x86_64-linux'

  stack-build:
    name: Stack lts-19
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          enable-stack: true
      - uses: freckle/stack-cache-action@v2.0.3
      - run: stack build --only-dependencies
      - run: stack build
      - run: stack build --haddock

  cabal-build:
    name: Cabal with GHC ${{ matrix.ghc }}
    strategy:
      fail-fast: false
      matrix:
        ghc: [ '8.10.7', '9.2.4' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cabal
            dist-newstyle
          key: cabal-cache-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal') }}
      - run: cabal build all --only-dependencies
      - run: cabal build all
