name: CI

on:
  pull_request:
  push:

jobs:

  nix-build:
    name: Nix build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v17
      - name: Build all packages
        run: nix build -L .#docs
      # - name: Build devShell
      #   run: nix build -L '.#devShells.x86_64-linux.hacking-on-purenix' '.#devShells.x86_64-linux.use-purenix'

