name: CI

on:
  push:

jobs:

  nix-build-docs:
    name: Nix build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v17
      - name: Build all packages
        run: nix build -L .#docs

  nix-build-server:
    name: Nix build server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
      - name: Build binplz-server
        run: nix build -L '.#server'
      - name: Build binplz-server shell
        run: nix build -L '.#devShell.x86_64-linux'

  stack-build:
    name: Stack lts-19
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          enable-stack: true
      # Caching setup copied from https://github.com/actions/cache/blob/main/examples.md#haskell---stack
      - uses: actions/cache@v3
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-global-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('**/*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-stack-global-
      - uses: actions/cache@v3
        name: Cache .stack-work
        with:
          path: .stack-work
          key: ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/*.hs') }}
          restore-keys: |
            ${{ runner.os }}-stack-work-
      - run: stack build --only-dependencies
      - run: stack build

  cabal-build:
    name: Cabal with GHC ${{ matrix.ghc }}
    strategy:
      fail-fast: false
      matrix:
        ghc: [ '8.10.7', '9.2.4' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      # Caching setup copied from https://github.com/actions/cache/blob/main/examples.md#haskell---cabal
      - name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
        uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}
          restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-
      - run: cabal build all --only-dependencies
      - run: cabal build all
      - run: cabal haddock all
